Feature: Introduce new class called CalistaEngine and add new function called rlike()
Aubay-Data-AI/calista pull request #6
Opened 2024-07-23 13:18 UTC by msaounera9610

- Introduce new class called CalistaEngine
- Implement where feature allowing user to execute check on data subset
- Complete types in mapping_type in each engine
- update AggregateCondition agg_col_name method to make it uppercase and also update sql get_schema
- update functions.py docstrings to replace CalistaTable by CalistaEngine
- add new function called rlike()
- rename groupBy() function with group_by()
- update tests

2024-07-23 13:44 UTC, Peter-Aubay requested changes
Add tests for filter feature et ensure that sphink doc is up to date

2024-07-24 13:49 UTC, Flexron approved these changes

2024-07-24 13:58 UTC, marine-tk approved these changes

2024-07-24 14:00 UTC, Peter-Aubay approved these changes

2024-07-24 14:03 UTC, merged